site_id = "gt"
title = "Golden Idea Theme"
baseurl = "https://golden-idea.github.io"
copyright = "Copyright 2018, GoAndMake.app"
ghdata_provider = "github"
ghdata_repo_owner = "themedata"
ghdata_repo_name = "golden-idea"

[menu]

  [[menu.global]]
  url = "/"
  name = "Home"
  menu = "global"
  identifier = "tutorials"
  pre = ""
  post = ""
  weight = 1.0
  parent = ""

  [[menu.global]]
  url = "/about/"
  name = "About"
  menu = "global"
  identifier = "about"
  pre = ""
  post = ""
  weight = 10.0
  parent = ""

  [[menu.iconmenu]]
  url = "https://github.com/golden-idea/golden-idea.github.io"
  name = "Demo Site Repo"
  menu = "iconmenu"
  identifier = ""
  pre = "Fork Me"
  post = ""
  weight = 1.0
  parent = ""

[params]
absolutebuilderurl = true
accent_color = "hsl(165,35%,45%)"
accent_color_light = "hsl(165,35%,65%)"
custom_css = "\n@keyframes slowRightEntry {\n  0% {\n    transform: translateX(-100vw);\n    opacity: 0.3;\n  }\n50% {\n   opacity: .5;\n}\n\n  90% {\n   transform: translateX(0vw);\n   opacity: .8;  \n   }\n  100% {\n    transform: translateX(0vw);\n   opacity: 0.7;\n}\n}\n\n.slowRightEntry {\n  animation: slowRightEntry 10s linear 10;\n  height: 100%;\n  }\n\n\n@keyframes slowRightExit {\n  0% {\n    transform: translateX(0vw);\n   opacity: 1;\n  }\n\n  50% {\n    opacity: .1;\n }\n  100% {\n   opacity: .0;\n    transform: translateX(50vw);\n  }\n}\n\n.slowRightExit {\n  animation: slowRightExit 20s linear 5;\n  height: 100%;\n}\n"
flex_box_interior_classes = "w-100 w-50-m w-33-l "
gt_author_name = "GoAndMake.app"
gt_author_url = "https://we.goandmake.app"
gt_license_name = "CC-BY-NC-4.0"
gt_license_url = "https://creativecommons.org/licenses/by-nc/4.0/"
gt_theme_name = "Golden Idea"
header_class = "bg-primary-color"
lightness = 45.0
lightness_dark = 20.0
lightness_light = 65.0
lightness_lighter = 80.0
logo_url = "/images/logos/icon-on-dark.svg"
mainSections = [
  "post"
]
main_menu_align = "start"
mainsections = [
  "post"
]
primary_hue = 353.0
saturation = 35.0
skip_cover_nav = false
gh_provider = "github"
gh_repo_owner = "golden-idea"
gh_repo_name = "golden-idea.github.io"
gh_repo_image = [
  "images/avatar-brown.jpg",
  "images/avatar-chocalate.jpg",
  "images/avatar-cyan.jpg",
  "images/avatar-gingerbread-house.jpg",
  "images/avatar-gingerbread-xmas.jpg",
  "images/avatar-gingerbread.jpg",
  "images/avatar-pink.jpg",
  "images/avatar-pinkrose.jpg",
  "images/avatar-rosy.jpg",
  "images/avatar-white.jpg",
  "images/c.jpg",
  "images/coffee-apples.jpg",
  "images/coffee-beans-ground.jpg",
  "images/coffee-beans-in-white-mug.jpg",
  "images/coffee-beans.jpg",
  "images/coffee-bread.jpg",
  "images/coffee-brewing.jpg",
  "images/coffee-cake.jpg",
  "images/coffee-cups-green.jpg",
  "images/coffee-deck.jpg",
  "images/coffee-desserts.jpg",
  "images/coffee-doughnuts.jpg",
  "images/coffee-hands-3.jpg",
  "images/coffee-heart.jpg",
  "images/coffee-macarons-p.jpg",
  "images/coffee-plants.jpg",
  "images/coffee-shop.jpg",
  "images/coffee-toffee.jpg",
  "images/logos/icon-on-dark.svg",
  "images/logos/icon-on-light.svg",
  "images/logos/logo.svg"
]
css_url = "https://fonts.googleapis.com/css?family=Gloria+Hallelujah"

  [params.global_section]

  [params.js_export]

  [params.js_partial]

  [[params.mobile_menu_button]]
  label = "Menu"
  menu = "global"

  [[params.mobile_menu_button]]
  label = "Account"
  menu = "iconmenu"
